# Generated by Django 3.2.6 on 2021-08-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='Artista Principal do Evento?'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, max_length=300, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=100, verbose_name='Link pra compra'),
        ),
        migrations.AlterField(
            model_name='imagemhome',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
