# Generated by Django 3.2.6 on 2021-08-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_evento_dataevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='posicao',
            field=models.CharField(choices=[('Esquerda', 'Esquerda'), ('Direita', 'Direita')], default='Esquerda', max_length=8, verbose_name='Posição no card do evento'),
        ),
    ]
